name: Release
on:
  push:
    branches:
      - main

jobs:
  ruff:
    name: ruff
    uses: ./.github/workflows/ruff.yml
  pytest:
    name: pytest
    uses: ./.github/workflows/pytest.yml
  release:
    name: Release
    needs: [ruff, pytest]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          npx --package=semantic-release \
              --package=@semantic-release/git \
              --package=semantic-release-pypi \
              semantic-release
