name: Ruff
on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_call:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v2
